tools:
    shell:
        allow:
            - grep *
            - cd *
            - cargo build
            - find *
            - head *
            - echo *
            - ls *
            - sort
            - cargo check
            - tail *
